In [1]:
import numpy as np
import pandas as pd

### Finding Missing Data

In [2]:
data = {
    "Name": ["Alice", "Bob", "Charlie", "David"],
    "Age": [24, np.nan, 22, 30],
    "Country": ["USA", "UK", None, "Canada"]
}

df = pd.DataFrame(data)

print(df)

      Name   Age Country
0    Alice  24.0     USA
1      Bob   NaN      UK
2  Charlie  22.0     NaN
3    David  30.0  Canada

In [3]:
df.isna()

    Name    Age  Country
0  False  False    False
1  False   True    False
2  False  False     True
3  False  False    False

In [4]:
df.isna().sum()

Name       0
Age        1
Country    1
dtype: int64

In [5]:
df.isna().any()

Name       False
Age         True
Country     True
dtype: bool

### Removing Missing Data

In [6]:
df.dropna()

    Name   Age Country
0  Alice  24.0     USA
3  David  30.0  Canada

In [7]:
df

      Name   Age Country
0    Alice  24.0     USA
1      Bob   NaN      UK
2  Charlie  22.0     NaN
3    David  30.0  Canada

In [9]:
df.dropna(thresh=3)

    Name   Age Country
0  Alice  24.0     USA
3  David  30.0  Canada

In [10]:
df

      Name   Age Country
0    Alice  24.0     USA
1      Bob   NaN      UK
2  Charlie  22.0     NaN
3    David  30.0  Canada

In [11]:
df.fillna(0)

      Name   Age Country
0    Alice  24.0     USA
1      Bob   0.0      UK
2  Charlie  22.0       0
3    David  30.0  Canada

In [12]:
df

      Name   Age Country
0    Alice  24.0     USA
1      Bob   NaN      UK
2  Charlie  22.0     NaN
3    David  30.0  Canada

In [15]:
values = {'A':0, 'B':200, 'C':300,'D':400}
df.fillna(value=values)

      Name   Age Country
0    Alice  24.0     USA
1      Bob   NaN      UK
2  Charlie  22.0     NaN
3    David  30.0  Canada